--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Inaayat04/AntiGamingChair
build-by-default: true
branches:
- master
projects:
  AntiGamingChair:
    path: ""
    icon: "icon.jfif"
    lint:
      phpstan: false
...
